### ISSUE TITLE
Popup after adding attributes

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/CODAP#1]
When you click the "Save" button after adding attributes, a popup should appear indicating to the user that their contribution has been registered.

**Comment by staubibr** [comment]
I added the saved popup. I put a temporary note saying that modifications are not saved in the beta version. We can remove it once the save function is coded.

I guess I'll leave it open until we complete the save function so we don't forget about the note.

**Comment by Noznoc** [comment]
Sounds good. Thank you Bruno!

**Comment by staubibr** [comment]
The save function works, I removed the message. It'll be available as soon as commit my code, tomorrow or friday.
