### ISSUE TITLE
Submission Pop-up

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/CODAP#10]
We should have some kind of pop-up that occurs after a user clicks the ``Submit` button.

E.g., `Thank you for your submission, your contribution should appear in OSM in ___ minutes` ... 

Jean and Christine, any suggestions on the text?

**Comment by staubibr** [comment]
WE used to have a popup, I took it out by mistake.

**Comment by staubibr** [comment]
The popup is back, the text only reads something like "modifications to the record have been saved". Do I need to change it?

**Comment by Noznoc** [comment]
Thank you! That's good for now.

**Comment by Noznoc** [comment]
Closing
