### ISSUE TITLE
Add tutorial

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/CODAP#2]
Add tutorial demonstrating how to use the app.

**Comment by staubibr** [comment]
What's happening with the tutorial? Did you have a chance to prepare it?

**Comment by Noznoc** [comment]
I thought I sent it to you about a month ago! I am currently at the Innovation Lab so I cannot access my emails right now. Maybe check your emails to see if I did send it; if not, let me know and then I resend it in the afternoon.

**Comment by staubibr** [comment]
Ok found it in my Outlook box, I was looking in my gmail box before. I should have time to include it for monday.

**Comment by staubibr** [comment]
Added the tutorial and changed the mailto link for Contact. I also translated the tutorial. Will be deployed in a day or two.
