### ISSUE TITLE
In Settings, add French License section

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/CODAP#3]
Copy and paste the license text from the repo.

**Comment by staubibr** [comment]
I added the license section. The french version is empty, we need to get a translation. I remember Alessandro saying Margaret was supposed to provide a translation. Am I remembering correctly?

**Comment by Noznoc** [comment]
Great! Alessandro and I were reviewing the French section, so that's why we didn't notice the license section. 

I believe you are correct regarding the translation. Will send you a translated version within this week or next week.

Thanks!

**Comment by Monduiz** [comment]
Yes, im still waiting on her.

**Comment by staubibr** [comment]
Anything new with the french license?

**Comment by Monduiz** [comment]
I talked with @Noznoc today and they will follow-up with IMD for the French version.

**Comment by Noznoc** [comment]
Sent in license for translation.

**Comment by staubibr** [comment]
I added the licence. I think Julia already modified the md file in the repo too.
