### ISSUE TITLE
iPhone 5 SE View Error

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/CODAP#8]
Christine and I both have an iPhone 5 SE. When we tested the app on our cells, the initial pop-up asking for us to log into OSM does not appear. 

To see the pop-up, we had to turn our mobile phones to landscape mode and then turn our phones back to portrait.

**Comment by staubibr** [comment]
This is a tough issue to debug since I don't have an iPhone. I don't think I can get it done by monday

**Comment by staubibr** [comment]
I tried to change something with the CSS, can you try it again?

**Comment by Noznoc** [comment]
Seems to be working for me now. Will close this issue for now.
